### ISSUE TITLE
Error on console on startup

### ISSUE THREAD

**Issue by ghost** [lucasGithuber/Element-Manipulation#1]
Description -> Title

Steps to reproduce the Issue -> Add the latest version of Element-Manipulation ( DEV3 -git b57c2 ) and start the server

Expected behavior -> There should not be any error

Server Log / Error Report -> https://pastebin.com/BtX6t99F

Environment ->
 - Minecraft Version: 1.18.1
 - CS-CoreLib Version: None
 - Slimefun Version: Dev990
 - Plugin Version: ( DEV3 -git b57c2 )

**Comment by lucasGithuber** [comment]
Known warning
Working on it
