### ISSUE TITLE
The Element description wrong

### ISSUE THREAD

**Issue by haiman233** [lucasGithuber/Element-Manipulation#4]
## Description (Required)
The information of TRANSITION_METALS and NOBLE_GASSES shows 'other metals'.
The Symbol of Selenium , Indium and Seaborgium is wrong
The name of COPERNICIUM is wrong
The Atomic number of Oganesson is wrong
the Atomic mass of Nihonium is [284]
The Atomic mass of Livermorium has one more ]

## Environment (Required)

 - Minecraft Version:
 - CS-CoreLib Version:
 - Slimefun Version:
 - Plugin Version:

**Comment by lucasGithuber** [comment]
damn sorry i didnt see this :sob:

**Comment by lucasGithuber** [comment]
fixed bro so helpful
